### PR TITLE
add documentation for sendNotificationError

### PR DESCRIPTION
**Pull request by jasonwaters**
## Description

We recently added a feature to subscribe to sendNotification errors.  This PR documents it in the troubleshooting section so customers can find how to do so.

## Related Issue

- https://jira.corp.adobe.com/browse/TNT-45561
- https://jira.corp.adobe.com/browse/TNT-45232

### CODE REVIEW

**Comment by jasonwaters** [comment]
@adobe/open-source-office I have been contributing to repos on the Adobe github org for years now and signed the CLA a long time ago.  But recently I opened this PR on the AdobeDocs org and the Adobe CLA Bot is telling me I have not signed the CLA.  Any tips?

**Review by dcottingham — APPROVED** [review]
LGTM

**Comment by jasonwaters** [comment]
Hi @judy-kim can you review this when it's convenient?

**Review by judy-kim — APPROVED** [review]
Our code syntax highlighter may not support `java` -- historically, the workaround has been to use `javascript` instead of `java`. However, if everything is now rendering as expected, ignore this comment

**Pull request merged**
